### ISSUE TITLE
Does it support React Native?

### ISSUE THREAD

**Issue by ykcadcg** [microsoft/cognitive-services-speech-sdk-js#116]
RN supports WebSockets https://facebook.github.io/react-native/docs/network.html, and your sdk supports browser. Does it mean it's a smooth match? Or any pitfall to note?

**Comment by rozele** [comment]
@ykcadcg you could look at whether `react-native-webrtc` is compatible with this library. Just a note, I attempted this for iOS and `cordova-plugin-iosrtc` and didn't have any success, but the React Native module may have better compatibility.

I'd recommend trying the `registerGlobals` method: https://github.com/react-native-webrtc/react-native-webrtc#registerglobals.

**Comment by oscholz** [comment]
@ykcadcg @rozele we haven't tested the JavaScript Speech SDK with React Native yet, but we don't know of anything that should stand in the way of using the two together. We encourage you to give it a try. There is a chance that you will encounter some issues. We had a customer that used the JavaScript Speech SDK with Angular, and ran into a tools issue. This was technically a bug in the tool, but we were able to make a change in our code to work around the issue. 
So if you try this, and find an issue, please reactivate this issue, and let us know what you found. We'll be happy to try to help.

Thank you for using the JS Speech SDK!

**Comment by anilsamuel** [comment]
Get the error below in expo; shall I open a new issue ?

Failed building JavaScript bundle.
The package at "node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/CertChecks.js" attempted to import the Node standard library module "url". It failed because the native React runtime does not include the Node standard library. Read more at https://docs.expo.io/workflow/using-libraries/#using-third-party-libraries

**Comment by joostlawerman** [comment]
It seems compatible with the RN webrtc module. On mic recordings it still requires `AudioContext` which is only available on the web.

Did anyone find a workaround for this?
