### ISSUE TITLE
Are non-.wav (.mp3, .mp4, .flac) audio files supported with this SDK?

### ISSUE THREAD

**Issue by timtutt** [microsoft/cognitive-services-speech-sdk-js#175]
Per the documentation here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=debian&pivots=programming-language-csharp, there is additional configuration required for supporting types other than `.wav`. 

Unfortunately there is no documentation for how to do so in the Javascript SDK yet that I can find, and searching around this repo, I have not found similar api calls. Will this be supported in the javascript SDK near term?

**Comment by lisaweixu** [comment]
The current SDK only support PCM format in Javascript. We don't have this in our roadmap yet. You are welcomed to contribute to the SDK since it is open source.

**Comment by oscholz** [comment]
@timtutt we are going to resolve this for now, since we answered the question. If you have a specific use case in mind that would make this a high priority for us to add, please let us know. If you want to help do this work, please feel free to contribute to the project under our [Contributing guidelines](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/README.md#contributing).
Thank you for using the JS Speech SDK!
