### ISSUE TITLE
IPhone IOS not sending audio when using video chat with Speech to Text Conversation Translator

### ISSUE THREAD

**Issue by brandom-msft** [microsoft/cognitive-services-speech-sdk-js#243]
Opening on behalf of @nuenook

**Describe the bug**
My website is Video Chat, so I want to use Speech to text translation on my website
but when I turn on Speech to text, Safari cannot send audio, in the other hand when try to restart audio it can send audio but no translation text, it seems safari only reserve one Microphone?

**To Reproduce**

goto my example web https://nuenook.github.io/ then click allowed Mic/Video
test Speaking, I can hear myself
Start Speech to text by input token/region then click start Speaking
The text is shown but I cannot hear myself anymore
Example webRTC from https://webrtc.github.io/samples/
Room Translator from https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/browser/multi-device-conversation

**Expected behavior**
If not bug, do you have a solution or guide for solving?

**Version of the Cognitive Services Speech SDK**
"microsoft-cognitiveservices-speech-sdk": "^1.13.0"

**Platform, Operating System, and Programming Language**

OS: IOS 14
Hardware - Iphone 8
Programming language: JavaScript
Browser Safari
Additional context
It happens only Safari on iPhone, Safari on Mac is working

Thank you

**Comment by brandom-msft** [comment]
@nuenook 

Can you share more detail on what specifically is failing? From your post, I gather that the audio is not made accessible where you would expect it to be but I'm not sure if this is an issue with the code or if it's a limitation of some part of your project. For example, I found [this article about simultaneous mic access on iPhone](https://forums.macrumors.com/threads/simultaneous-microphone-access-on-ios.1960007/), but with the details above I'm not able to say for certain if this is what you're running into or not.

Any extra detail you can provide would be helpful, like if there's an issue during a specific API call or perhaps an object is not getting audio when you expect it would, etc.

**Comment by nuenook** [comment]
I think I have the same problem with your attached link, so if we cannot use two AudioTrack in Safari, my expectation is the Conversation Translator is possible to push the current Audio's stream track instead of using by `startTranscribingAsync`?
I look in documents it has pullStreamInput/Output on AudioConfig but not sure it's working with Conversation Translator since I cannot found that Example.

**Comment by enricop89** [comment]
For the Microsoft folks: this bug is related to https://bugs.webkit.org/show_bug.cgi?id=179363. As you can see from the description, If a getUserMedia() requests a media type requested in a previous getUserMedia(), the previously requested media track's 'muted' property is set to true, and there is no way to programmatically unmute it.

Which is exactly what's happening when using a video chat SDK along with Microsoft SDK.

I opened the https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/260 to solve the issue. The idea is to inject to the Microsoft service the same track used on the first GetUserMedia so we don't have to call a second one and avoid the bug above.

**Comment by brandom-msft** [comment]
@nuenook Did this resolve your issue?

**Comment by nuenook** [comment]
@brandom-msft Yes! it working on iPhone now.

I found a little thing that when `stopTranscribingAsync` then `startTranscribingAsync` again, the Speech to Text did not respond so, I already solved it by stopped a stream from MediaStream instead Like 
```js
/** STOP  */
audioMediaStream
	.getTracks()
        .forEach((track) => (track.enabled = false))

/** START */
audioMediaStream
	.getTracks()
        .forEach((track) => (track.enabled = true))
```

But I saw in PR, this problem will resolve in the next release. 
I will wait for the next version.
Thank you
