### ISSUE TITLE
Error when using 'KeywordRecognitionModel'

### ISSUE THREAD

**Issue by manish-95** [microsoft/cognitive-services-speech-sdk-js#246]
I am using the npm package of microsoft-cognitiveservices-speech-sdk version 1.13.1. When I try to use the KeyWordRecognitionModel to start Speech Recognition based on the Custom Keyword getting recognized successfully, I get an error that says `Error: Not yet implemented`. Is this due to the fact that the feature is not yet available in the javascript sdk? If so, is there a tentative timeframe for including this in the javascript version? Please find below a screenshot of the error.

![image](https://user-images.githubusercontent.com/29098159/94544261-a602fc80-0268-11eb-8e75-79d4510bab93.png)

**Comment by glharper** [comment]
@manish-95 Thanks for submitting this issue. KeywordRecognitionModel is indeed not yet available in the JS SDK. The python implementation will be in our next release, 1.14, but the timeline for the JS implementation is TBD.

**Comment by TheLogan** [comment]
Ooh, I came here for the same.
The class and functions really ought to reflect their unfinished nature.

The error I get references this section of code
```
32 |        Contracts.throwIfFileDoesNotExist(fileName, "fileName");
33 | 
34 |        throw new Error("Not yet implemented.");
```

So I was thinking that the not yet implemented might be a false positive occurring because the file path was not working (spent way too long trying to get the filepath right xD )

**Comment by lino-silva** [comment]
@glharper is there a roadmap or any sort of indication to when this might be implemented?

**Comment by glharper** [comment]
@lino-silva I've just added this to our backlog, and we'll figure out the priority at our next grooming.

Thanks,
Glenn

**Comment by lino-silva** [comment]
@glharper thank you very much for your response - is there some way for me to keep up with those developments, or do I just wait and see?
Cheers and keep safe, Lino

**Comment by chevtek** [comment]
Is there a recommended alternative for keyword spotting in NodeJS? My team is creating a discord bot that provides voice recognition commands. We've implemented this ability using the Azure Speech JavaScript SDK and it works great except for the fact that it basically has to continuously recognize speech and then we have to parse the text to find the keyword and go from there.

This would be fine if it wasn't for the fact that in only a handful of days a single developer has racked up $10 from the voice recognition. When the bot goes live it will have to listen continuously for hours on end day in and day out. I am worried this is going to explode the cost here. Anything you recommend for getting around this? I was hoping keyword detection would greatly reduce processing costs but it appears we're out of luck here since there's no plans to implement it in the JavaScript SDK 😢
