### ISSUE TITLE
No Microphone Sound captured on iOS...even with Safari

### ISSUE THREAD

**Issue by madeInLagny** [microsoft/cognitive-services-speech-sdk-js#256]
Issue: 
When using microsoft.cognitiveservices.speech.sdk.bundle-min.js on iOS (iPad) and Safari, microphone sound is not captured.

Step to reproduce:

`navigator.mediaDevices
      .getUserMedia({
        audio: {
          sampleRate: 16000,
          channelCount: 1,
        video: false
      })`

No error is fired. 
However no sound is captured. This occurs on iPad and Safari, but works well with Chrome on other platform.
The issue seems to date back to version 1.12

**Comment by rhurey** [comment]
Safari has the attribute of requiring audio input / output being only allowed as a response to user input.

This is usually where things to wrong.

**Comment by madeInLagny** [comment]
True, but in this case, rolling back to version 1.12 of microsoft.cognitiveservices.speech.sdk.bundle-min.js within the same code solves the problem. IMO, it is not related to Safari.

**Comment by ralph-msft** [comment]
@madeInLagny, we are currently investigating this issue and will provide an update here as soon as we have a fix and/or workaround. We plan to get the fix in as part of our next release which should be soon.

**Comment by madeInLagny** [comment]
@ralph-msft Thank you. We will wait for the next release.

**Comment by rhurey** [comment]
One question... What iOS version are you using?

**Comment by madeInLagny** [comment]
13.6.1 on an iPad

Le sam. 17 oct. 2020 à 07:27, Ryan Hurey <notifications@github.com> a
écrit :

**Comment by rhurey** [comment]
So I didn't get a repro on my 13.6.1 iPhone, so I've got a few more questions.

Do you get a SessionStarted callback?
Does anything get logged to the console?

Can you try https://speechsdksample.azurewebsites.net/1.13.1.min/ ?
(It's the sample page from https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser)

**Comment by rhurey** [comment]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html

It's a straight copy from that.

**Comment by madeInLagny** [comment]
Well, still no luck in having it worked with Safari in my implementation. I noticed that there is no sessionStarted event nor any request from Safari to allow access to Microphone. Is there a getUserMedia method that is called on the demo page and that I miss in the example file ?

**Comment by compulim** [comment]
@madeInLagny are you using 1.12.0 or 1.13.x?

In 1.12.0-1.13.1, it seems the `webkitAudioContext` was accidentally removed ([in this PR](https://github.com/microsoft/cognitive-services-speech-sdk-js/commit/1bf9064a9ead3a3e4b27e070b1136dce77dafa17)), thus, it's not working.

Looks like the issue was resolved in 1.14.0.

### 1.13.1

Not working, without `webkitAudioContext`.

https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/v1.13.1/src/common.browser/MicAudioSource.ts#L311

### 1.11.0

Working, with `webkitAudioContext`.

https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/v1.11.0/src/common.browser/MicAudioSource.ts#L308

### 1.14.0

`webkitAudioContext` moved to `AudioStreamFormat.ts`. Should be working.

https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/v1.14.0/src/sdk/Audio/AudioStreamFormat.ts#L120

**Comment by madeInLagny** [comment]
Yes. Confirmed. 1.14.0 is now working on iOS. Thanks for the update

Le lun. 2 nov. 2020 à 22:27, William Wong <notifications@github.com> a
écrit :
