### ISSUE TITLE
User speech is only recognized once 

### ISSUE THREAD

**Issue by zdhz** [microsoft/cognitive-services-speech-sdk-js#281]
**Version**: 1.14.1
**Browser**: Chrome 87

Hello, when using the `DialogServiceConnector.listenOnceAsync()` function in version 1.14.1 of the SDK, the user's speech (from a microphone) is only recognized on the first turn. No user speech is recognized in future turns. 

- **1st attempt**: The first turn is executed correctly, user speech is recognized and all expected events/activities are received by the client. 

- **2nd attempt**: No user speech is detected from the microphone and the turn is cancelled.
We can see the following event handlers called: `sessionStarted`, `speechEndDetected`, `canceled` x2, `disconnected`.

- **3rd attempt, and all attempts after**: An error is thrown `Uncaught (in promise) Another turn started before current completed.`

This functionality works on version 1.13.1. Please let me know if you need any more info, or I can try and create a minimal reproduction.

Note: In Safari (version 14), the behaviour is slightly different, as the client also receives a `recognized` event on the 2nd attempt, however no text is sent with the event. This was not tested in version 1.13.1, as that version was missing the AudioContext polyfill.

**Comment by brandom-msft** [comment]
Hi @zdhz  - thanks for submitting the issue! This impacted other functionality and has since been addressed with #283 . I've just verified your repro and found it resolved by using the latest build from master. For an immediate remedy, you can create a private build off of master (steps [here](https://github.com/microsoft/cognitive-services-speech-sdk-js#building) in the README). We'll include the fix in the next release, in coming weeks.

I'm closing the issue as resolved but please reply back with any questions related to the above. Thanks!
