### ISSUE TITLE
Using incorrect key doesn't produce error about key

### ISSUE THREAD

**Issue by diberry** [microsoft/cognitive-services-speech-sdk-js#305]
I accidentally used by ComputerVision key in the following code. I didn't receive an error about the incorrect key. My code errored when I tried to read the audioData.byteLength. It seems synthesizer.speakTextAsync should have returned something about a wrong key. Using express server for API. 

`    app.get('/text-to-speech-file', (req, res) => {

        const filename = `./stream-from-file-${timeStamp()}.mp3`;

        const { key, region, phrase } = req.query;

        const speechConfig = sdk.SpeechConfig.fromSubscription(key, region);
        const audioConfig = sdk.AudioConfig.fromAudioFileOutput(filename);
        speechConfig.speechSynthesisOutputFormat = 5; // mp3
        const synthesizer = new sdk.SpeechSynthesizer(speechConfig, audioConfig);

        synthesizer.speakTextAsync(
            phrase,
            result => {
                const { audioData } = result;
                console.log(`Audio data byte size: ${audioData.byteLength}.`); // this line errors with wrong key
                const audioFile = fs.createReadStream(filename);
                res.set({
                    'Content-Type': 'audio/mpeg',
                    'Content-Length': audioData.byteLength
                });
                audioFile.pipe(res);
                synthesizer.close();
            },
            error => {
                console.log(error);
                synthesizer.close();
                res.send(error);
            });
    });`

**Comment by glharper** [comment]
@diberry Thank you for logging this issue. Codewise, using the wrong key will result in a Cancelled event/result, so you will receive a result back, not an error. From (this sample)[https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/node/synthesis.js], there is a SynthesisCanceled callback included, the comment mentioning that errors are within the remit of Canceled results. (If you wish to handle the Cancelled result in the speakTextAsync result callback, checking if the value of the result.reason is ResultReason.Canceled also works.)

Philosophically, the Speech SDK does not and cannot internally judge the validity of a given subscription key. It can only report back the results from the backend when attempting to use that key, which is why the Cancelled event is emitted in this scenario, not an internal error.
