### ISSUE TITLE
Stringified UUID is invalid

### ISSUE THREAD

**Issue by ShahidBhat** [microsoft/cognitive-services-speech-sdk-js#326]
Hi,

I recently updated the sdk version to the latest one, after deployment I started to receive an "Stringified UUID is invalid" error message when it tries to pass the speech subscription key. 

These are the versions of my libraries.
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0", 
    "microsoft-cognitiveservices-speech-sdk": "^1.15.1"

The solution seems to work fine in local after deployment I get this error.

Please advise what needs to be fixed?

**Comment by glharper** [comment]
@ShahidBhat, thank you for writing up this issue and using Speech SDK. Googling this issue, I found [this comment](https://github.com/uuidjs/uuid/issues/508#issuecomment-677460598). Could you try upgrading to Angular 9.1.12 or higher?

**Comment by glharper** [comment]
@ShahidBhat Was the above suggestion helpful? If there are no follow-up questions, this issue will be closed within the next 48 hours.

**Comment by ShahidBhat** [comment]
Hi, as per the suggestion I have upgraded my Angular version in the project and the stringified error is now gone. However as I start the speechrecognition it starts and fails quickly with the following error in the console 
"Refused to create a worker from 'blob:https://....../836b0131-77ba-4d2e-85f5-ce7296632857' because it violates the following Content Security Policy directive: "script-src 'self' http://xxxx 'unsafe-inline' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback."

**Comment by ShahidBhat** [comment]
Hi, as per the suggestion upgrading the Angular version resolved the stringified error, However as I start the recognition process I get an error in the console with the following message 
_Refused to create a worker from 'blob:https://test.com/457554f2-08b9-45e8-bb80-ac1685a2f4ff' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback._

**Comment by glharper** [comment]
@ShahidBhat If you're using SpeechSDK in a page with the Content Security Policy set, [this Stack Overflow question](https://stackoverflow.com/questions/54695310/getting-refused-to-create-worker-from-blob-error-in-video-min-js-when-looking/56534720) may help.

**Comment by Fradulentus** [comment]
Прошу дать объяснения по поводу того, почему корпоративные каналы связи предоставляют возможность вкладывать в передаваемое сообщение или сигнал иные формы существования. Сейчас в частности я говорю о ссылках. Прошу разобраться с данным вопросом в самое ближайшее время.

Отправлено из приложения "Почта<https://go.microsoft.com/fwlink/?LinkId=550986>" для Windows9

От: ***@***.***>
Отправлено: 20 апреля 2021 г. в 16:48
Кому: ***@***.***>
Копия: ***@***.***>
Тема: Re: [microsoft/cognitive-services-speech-sdk-js] Stringified UUID is invalid (#326)


Hi, as per the suggestion upgrading the Angular version resolved the stringified error, However as I start the recognition process I get an error in the console with the following message
Refused to create a worker from 'blob:https://test.com/457554f2-08b9-45e8-bb80-ac1685a2f4ff' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
