### ISSUE TITLE
how to set Speaking speed on tts?

### ISSUE THREAD

**Issue by eliyahuKriel** [microsoft/cognitive-services-speech-sdk-js#364]
hi guys
i able to set _voice_ and _lang_
I want also to change the **speed** of the voice , i cant find in the docs and in the **speechConfig** this property

i have this code :

`
const ttsSdk = require("microsoft-cognitiveservices-speech-sdk");
`

`const speechConfig = ttsSdk.SpeechConfig.fromSubscription(process.env.TTS_SUBSCRIPTION_ID, process.env.TTS_REGION);
`
`
 speechConfig.speechSynthesisVoiceName  =   selected_voice;
`
`
 speechConfig.speechSynthesisLanguage =  selected_lang;
`

any ideas?
thanks!

**Comment by glharper** [comment]
@eliyahuKriel You can use the "prosody rate" element in SSML to change the speed of the voice, for example:
```
<prosody rate="-20%">
  I'm speaking a little slowly here
</prosody>
<prosody rate="40%">
  But now I'm speaking really fast
</prosody>
```

[Text to Speech | Microsoft Azure](https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech/#features) halfway down has a box where you can quickly try things (and boilerplate SSML to modify).

Thanks for using Speech SDK, and taking the time to ask about this feature!

**Comment by eliyahuKriel** [comment]
@glharper thanks, i know that i can use the ssml format
but i want to use the **object** format, 
` synthesizer.speakTextAsync ` and note `speakSsmlAsync`
Too bad there is no such possibility with the object format
thanks anyway

**Comment by aytekin-smartcar** [comment]
Any update here?

**Comment by alexsorokoletov** [comment]
Hi!
Wanted to share some feedback on how SpeechSDK behaves w/regards to `speakTextAsync` and `speakSsmlAsync` and TTS speed.

`speakSsmlAsync` behaves differently on some phrases with words that are international. 
For example, phrase `Super! Je m'apelle Alex` starts as `Zuper` (german-ish) and then rest of the phrase is read in French.

It is possible to generate a more advanced SSML markup and tell it to use a specific voice (some voices still switch to other languages still). So a task of adjusting a speed of TTS becomes more difficult because of all that.
