### ISSUE TITLE
SpeechRecognizer: NBest results not ordered by confidence

### ISSUE THREAD

**Issue by yoshigev** [microsoft/cognitive-services-speech-sdk-js#368]
Hi,

We are using the `startContinuousRecognitionAsync` function, and set `OutputConfig` to `detailed` for receiving all the recognition alternatives (using the url: `wss://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?format=detailed&language=de-DE`).
The alternatives are returned in the `NBest` array, with the first element usually the best alternative (this is documented in the comment [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html#L630)).

We noticed cases that this is not the case, and the array is not ordered correctly by the confidence level.
This can also be seen on the `DisplayText`, which shows the first alternative although not with the highest confidence.
Moreover, only the first alternative has its text capitalized and punctuated, which also indicate that this is the chosen alternative.

This is the output we get:
```json
{
  "Id": "09ead3d232424aaface852bcc077cd23",
  "RecognitionStatus": "Success",
  "Offset": 23300000,
  "Duration": 19600000,
  "DisplayText": "Fritz Koff, Petra.",
  "NBest": [
    {
      "Confidence": 0.7548061,
      "Lexical": "fritz koff petra",
      "ITN": "fritz koff petra",
      "MaskedITN": "fritz koff petra",
      "Display": "Fritz Koff, Petra."
    },
    {
      "Confidence": 0.8077276,
      "Lexical": "spritzkopf petra",
      "ITN": "spritzkopf petra",
      "MaskedITN": "spritzkopf petra",
      "Display": "spritzkopf petra"
    },
    {
      "Confidence": 0.7193424,
      "Lexical": "pritzkow petra",
      "ITN": "pritzkow petra",
      "MaskedITN": "pritzkow petra",
      "Display": "pritzkow petra"
    },
    {
      "Confidence": 0.84936327,
      "Lexical": "fritz kopf petra",
      "ITN": "fritz kopf petra",
      "MaskedITN": "fritz kopf petra",
      "Display": "fritz kopf petra"
    },
    {
      "Confidence": 0.76341444,
      "Lexical": "fritz koff petra",
      "ITN": "fritz koff petra",
      "MaskedITN": "fritz koff petra",
      "Display": "fritz koff petra"
    }
  ]
}
```

#### Expected result
Having the "fritz kopf petra" alternative first , with proper capitalization and punctution.
Or, having a higher confidence level to the "Fritz Koff, Petra." alternative.

#### Actual result
The "Fritz Koff, Petra." appears first although it is not with the highest confidence.

Thanks,
Yehoshua

**Comment by mayrbenjamin92** [comment]
Hi there!

is there already some progress here? I'd love to get this fixed as this is actually a pretty severe one!

Best regards @ryanbodrug-microsoft

**Comment by glharper** [comment]
@yoshigev @mayrbenjamin92 This is expected behavior. From the [FAQ](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/faq-stt#i-get-several-results-for-each-phrase-with-the-detailed-output-format--which-one-should-i-use-):
"Always take the first result, even if another result ("N-Best") might have a higher confidence value. The Speech service considers the first result to be the best. It can also be an empty string if no speech was recognized.

The other results are likely worse and might not have full capitalization and punctuation applied. These results are most useful in special scenarios such as giving users the option to pick corrections from a list or handling incorrectly recognized commands."
