### ISSUE TITLE
Unable to connect: StatusCode: 500, Protocol "http:" not supported. Expected "https:"

### ISSUE THREAD

**Issue by marcelgoya** [microsoft/cognitive-services-speech-sdk-js#458]
OS: Sangoma Linux 7 (Core) / CentOS 7
Environment: Node.js v14
SDK: "microsoft-cognitiveservices-speech-sdk": "1.19.0"

I am running into the following connection issue once I run my client code on my server. The code works perfectly on my workstation. I turned off my firewall on the server and everything is whitelisted, so I have the suspicion that it could be related to the operating system. 

Any help or pointers into the right direction are greatly appreciated.

Error:

`ErrorDetails=Unable to contact server. StatusCode: 500, undefined Reason: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"`

Code:

```
  const speechConfig = sdk.SpeechConfig.fromSubscription('ABCD', 'westeurope');
      speechConfig.speechSynthesisVoiceName = 'en-IN-NeerjaNeural'; 
      const synthesizer = new sdk.SpeechSynthesizer(speechConfig, undefined);
      
      synthesizer.speakTextAsync(text,
        async (result) => {
          // const { audioData } = result; // Arraybuffer object
          synthesizer.close();

          console.log(result);
  },
        (error) => {
          console.log(error);
          synthesizer.close();
          Sentry.captureException(error);
          APM.endTransaction(transactionId, 500);
          reject();
        });
```

**Comment by ianjakobs** [comment]
Did you find a solution for this?

I've been running into the same issue, and I suspect it's because of [this change](https://github.com/getsentry/sentry-javascript/pull/3950) in the Sentry JavaScript SDK (which you appear to be using as well). It seems this SDK doesn't explicitly set a protocol, and therefore Sentry falls back to `http` which then causes the error.

I've tried removing the Sentry wrapper from my API handler, and also passing along an explicit `https` endpoint by using `sdk.SpeechConfig.fromEndpoint` instead of `sdk.SpeechConfig.fromSubscription`, but neither worked. For now I've had to downgrade to `@sentry/nextjs@6.12.0`, which certainly isn't ideal but then at least it works.

**Comment by alexsprings** [comment]
I'm running into the same issue after adding Sentry. Any updates here? I don't think downgrading Sentry is a good option

**Comment by lengyeld** [comment]
Same here! And we don't really want to downgrade sentry because of this

**Comment by ianjakobs** [comment]
Still the same here too. At this point I've update Sentry and just disabled it on the server for now, but I also opened up [a new issue](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/465) for this.
