### ISSUE TITLE
YourSubscriptionKey expire

### ISSUE THREAD

**Issue by AhmadFaraz-crypto** [microsoft/cognitive-services-speech-sdk-js#543]
When 'YourSubscriptionKey' has expired or invalid key. Throw the error key is invalid or your key has expired.

**Comment by glharper** [comment]
@AhmadFaraz-crypto Thank you for using Speech SDK, and writing this issue up. Help me understand what issue you'd like resolved. Would you like to see clearer wording of the "error key invalid" message?

I believe the websocket error (1006) for invalid credentials has multiple potential sources (for example, an SSL negotiation failure also throws a 1006), and the client doesn't have a good way of disambiguating between those sources. (So we don't necessarily know whether the 1006 is an SSL failure or an invalid key, for example.) Your perspective on how to navigate that ambiguity while making the error more understandable would be appreciated.

**Comment by glharper** [comment]
@AhmadFaraz-crypto I understand your frustration. Because the error was service-side (the client has no way of knowing whether a given key is expired or not), and the underlying network connection to the service was successful (at which point the service judged the key invalid and rejected the connection), our idiom is to return a Canceled Event with the somewhat cryptic error details: "Unable to contact server. StatusCode: 1006".

As mentioned before, these error details could be clearer, but that 1006 code can (and in practice, does) mean a lot of different malfunctions.
