### ISSUE TITLE
Behaviour discrepency between C++ and JS SDK for utterance result id

### ISSUE THREAD

**Issue by Tryptophan** [microsoft/cognitive-services-speech-sdk-js#638]
I am working to convert some code we've had on a frontend (JS) client that does speech translation to a C++ backend. We have noticed a difference in how both of these SDKs handle result ids from recognizing and recognized events.

In JS, the life of a translation (one utterance, eg. "The quick brown fox jumped over the lazy dog") will have the same result id until a "recognized" event ends the utterance. We've made use of this id to better track captions to prevent race conditions/etc.

In C++ the result id is never the same during the lifetime of a translation, making it difficult to track captions and update/display them. We opened a support ticket through azure and have an email thread going with the C++ team, but they claim that this is expected behavior. I will link this ticket in the thread so they have this context as well.

Can we get some clarity on this? Is this a bug with the JS or C++ side, because I would assume they follow the same spec.

Thank you!

**Comment by glharper** [comment]
@rhurey FYI.

**Comment by glharper** [comment]
@Tryptophan Thanks for using JS SDK, and writing this issue up. Help me to understand the exact issue with the JS SDK you're having? I'm reading this as "C++ SDK does not exhibit an expected behavior, but the JS SDK does". Is that fair? 

Naively, I'd expect the JS SDK behavior to be the least surprising to our customers, and I'd expect if I were to change the result id to be random for each sub-utterance, there'd be a few more issues opened in this repo.

**Comment by Tryptophan** [comment]
@glharper That's correct, the c++ does not behave as expected. Is it possible for the JS team to discuss with them and possibly describe this in further detail to follow the same spec? We're really looking for this functionality in the c++ sdk.

**Comment by glharper** [comment]
@Tryptophan I have informed the C++ team of this issue. Please open an issue [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues) so that they can track it. Closing here, as you note there's no bug in the JS behavior.
