### ISSUE TITLE
[feature] - Change punctuation config on demand

### ISSUE THREAD

**Issue by ygorlf** [microsoft/cognitive-services-speech-sdk-js#642]
**Feature Description**: I would like to know if its possible turn on and off the punctuation of my transcription without pause my recognition

**Scenario**: As a user I want to say a full sentence like: "My name is mike, I have 30 years and I am from New York." and after that disable the punctuation to say some specific info about the medic condition and transcribe that info without any punctuation like (comma, dot, exclamation mark, question mark)

I successfully disable the punctuation but can't find a way to enable back.

My code to disable punctuation:

```
this.speechConfig.setServiceProperty('punctuation', 'explicit');
```

**Comment by glharper** [comment]
@ygorlf Thanks for using Speech SDK, and writing this issue up. Because punctuation is set when the connection to the service is established, the punctuation setting can't be changed mid-recognition.
The code to enable it between recognitions would be:
`this.speechConfig.setServiceProperty('punctuation', 'none');`
