### ISSUE TITLE
canceled" [1] OBJ: string, "Unable to contact server. StatusCode: 1006, undefined Reason: undefined

### ISSUE THREAD

**Issue by vcombey** [microsoft/cognitive-services-speech-sdk-js#654]
Hi

I am receiving a cancel event with reason: "canceled" [1] OBJ: string, "Unable to contact server. StatusCode: 1006, undefined Reason: undefined" on the 'microsoft-cognitiveservices-speech-sdk' in javascript. this error happened as our usage has grown over the last weeks. Could it be the explaination  as mentioned in https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/new ?

how could we increase the number of allowed websocket connection to the azure speech to text service ?

Is the workaround mentioned in the previous issue a good idea ?
"Thinking of having 3-4 resources so I can add a round-robin logic with multiple keys."

thanks

**Comment by glharper** [comment]
@vcombey Thank you for using JS Speech SDK, and writing this issue up. Your link to a possible explanation just goes to the "file new issue" page, would you mind correcting it so that I better understanding what you're referring to?

For the workaround mentioned, having 3-4 resources with round-robin logic using multiple keys, yes, that's worth looking at as a mitigation strategy, if your usage is exceeding allowed rate limits on a single key.

**Comment by glharper** [comment]
Internal issue opened for this, closing this GH issue.
