### ISSUE TITLE
Blocked by chrome Content Security Policy

### ISSUE THREAD

**Issue by ILG2021** [microsoft/cognitive-services-speech-sdk-js#657]
Hello, everyone. I use Azure Speech sdk in a chrome extension. Because it is a every good method for cross platform. I create a chrome extension and use Azure speech sdk in options.html. But it is blocked when I use the functions.

`Timeout.js:11 Refused to create a worker from 'data:text/javascript;base64,IWZ1bmN0aW9uKGUpe3ZhciB0PXt9O2Z1bmN0aW9uIG4ocil7aWYodFtyXSlyZXR1cm4gdFtyXS5leHBvcnRzO3ZhciBvPXRbcl09e2k6cixsOiExLGV4cG9ydHM6e319O3JldHVybiBlW3JdLmNhbGwoby5leHBvcnRzLG8sby5leHBvcnRzLG4pLG8ubD0hMCxvLmV4cG9ydHN9bi5tPWUsbi5jPXQsbi5kPWZ1bmN0aW9uKGUsdCxyKXtuLm8oZSx0KXx8T2JqZWN0LmRlZmluZVByb3BlcnR5KGUsdCx7ZW51bWVyYWJsZTohMCxnZXQ6cn0pfSxuLnI9ZnVuY3Rpb24oZSl7InVuZGVmaW5lZCIhPXR5cGVvZiBTeW1ib2wmJlN5bWJvbC50b1N0cmluZ1RhZyYmT2JqZWN0LmRlZmluZVByb3BlcnR5KGUsU3ltYm9sLnRvU3RyaW5nVGFnLHt2YWx1ZTo...50TGlzdGVuZXIoIm1lc3NhZ2UiLCh7ZGF0YTplfSk9Pnt0cnl7aWYoImNsZWFyIj09PWUubWV0aG9kKXtjb25zdHtpZDp0LHBhcmFtczp7dGltZXJJZDpufX09ZTtPYmplY3Qoci5iKShuKSxwb3N0TWVzc2FnZSh7ZXJyb3I6bnVsbCxpZDp0fSl9ZWxzZXtpZigic2V0IiE9PWUubWV0aG9kKXRocm93IG5ldyBFcnJvcignVGhlIGdpdmVuIG1ldGhvZCAiJy5jb25jYXQoZS5tZXRob2QsJyIgaXMgbm90IHN1cHBvcnRlZCcpKTt7Y29uc3R7cGFyYW1zOntkZWxheTp0LG5vdzpuLHRpbWVySWQ6b319PWU7T2JqZWN0KHIuZCkodCxvLG4pfX19Y2F0Y2godCl7cG9zdE1lc3NhZ2Uoe2Vycm9yOnttZXNzYWdlOnQubWVzc2FnZX0saWQ6ZS5pZCxyZXN1bHQ6bnVsbH0pfX0pfV0pOw==' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.`

I think the continue recognize need a worker, the worker is block. So how to solve it? Our team is anxious to use Speech to Speech translate.

**Comment by ILG2021** [comment]
Can you give the complete code?

**Comment by glharper** [comment]
I can't give complete code, as we don't have an example chrome extension using JS Speech SDK. I can guess that your manifest should look like:
```
{
  // ...
  "content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; object-src 'self'; worker-src 'blob';"
  }
  // ...
}
```

But it's possible that also throws something like `'content_security_policy.extension_pages': Insecure CSP value "'blob'" in directive 'worker-src'.` You'll have to figure out how to make it work. One other possibility is using "worker-src: 'sha256-<SHA_OF_WORKER_CODE>'" to allow that worker to load.

**Comment by ILG2021** [comment]
How to find the SHA_OF_WORKER_CODE? The error code is from Azure Speech sdk, not the app.

Timeout.js in Azure Speech SDK

`// eslint-disable-next-line

const workerScript = \`!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=14)}([function(e,t,n){"use strict";n.d(t,"a",(function(){return i})),n.d(t,"b",(function(){return u})),n.d(t,"c",(function(){return a})),n.d(t,"d",(function(){return d}));const r=new Map,o=new Map,i=e=>{const t=r.get(e);if(void 0===t)throw new Error('There is no interval scheduled with the given id "'.concat(e,'".'));clearTimeout(t),r.delete(e)},u=e=>{const t=o.get(e);if(void 0===t)throw new Error('There is no timeout scheduled with the given id "'.concat(e,'".'));clearTimeout(t),o.delete(e)},f=(e,t)=>{let n,r;if("performance"in self){const o=performance.now();n=o,r=e-Math.max(0,o-t)}else n=Date.now(),r=e;return{expected:n+r,remainingDelay:r}},c=(e,t,n,r)=>{const o="performance"in self?performance.now():Date.now();o>n?postMessage({id:null,method:"call",params:{timerId:t}}):e.set(t,setTimeout(c,n-o,e,t,n))},a=(e,t,n)=>{const{expected:o,remainingDelay:i}=f(e,n);r.set(t,setTimeout(c,i,r,t,o))},d=(e,t,n)=>{const{expected:r,remainingDelay:i}=f(e,n);o.set(t,setTimeout(c,i,o,t,r))}},function(e,t,n){"use strict";n.r(t);var r=n(2);for(var o in r)"default"!==o&&function(e){n.d(t,e,(function(){return r[e]}))}(o);var i=n(3);for(var o in i)"default"!==o&&function(e){n.d(t,e,(function(){return i[e]}))}(o);var u=n(4);for(var o in u)"default"!==o&&function(e){n.d(t,e,(function(){return u[e]}))}(o);var f=n(5);for(var o in f)"default"!==o&&function(e){n.d(t,e,(function(){return f[e]}))}(o);var c=n(6);for(var o in c)"default"!==o&&function(e){n.d(t,e,(function(){return c[e]}))}(o);var a=n(7);for(var o in a)"default"!==o&&function(e){n.d(t,e,(function(){return a[e]}))}(o);var d=n(8);for(var o in d)"default"!==o&&function(e){n.d(t,e,(function(){return d[e]}))}(o);var s=n(9);for(var o in s)"default"!==o&&function(e){n.d(t,e,(function(){return s[e]}))}(o)},function(e,t){},function(e,t){},function(e,t){},function(e,t){},function(e,t){},function(e,t){},function(e,t){},function(e,t){},function(e,t,n){"use strict";n.r(t);var r=n(11);for(var o in r)"default"!==o&&function(e){n.d(t,e,(function(){return r[e]}))}(o);var i=n(12);for(var o in i)"default"!==o&&function(e){n.d(t,e,(function(){return i[e]}))}(o);var u=n(13);for(var o in u)"default"!==o&&function(e){n.d(t,e,(function(){return u[e]}))}(o)},function(e,t){},function(e,t){},function(e,t){},function(e,t,n){"use strict";n.r(t);var r=n(0),o=n(1);for(var i in o)"default"!==i&&function(e){n.d(t,e,(function(){return o[e]}))}(i);var u=n(10);for(var i in u)"default"!==i&&function(e){n.d(t,e,(function(){return u[e]}))}(i);addEventListener("message",({data:e})=>{try{if("clear"===e.method){const{id:t,params:{timerId:n}}=e;Object(r.b)(n),postMessage({error:null,id:t})}else{if("set"!==e.method)throw new Error('The given method "'.concat(e.method,'" is not supported'));{const{params:{delay:t,now:n,timerId:o}}=e;Object(r.d)(t,o,n)}}}catch(t){postMessage({error:{message:t.message},id:e.id,result:null})}})}]);\`;

const workerUrl = "data:text/javascript;base64," + btoa(workerScript);
const worker = new Worker(workerUrl);`

**Comment by hzubaca** [comment]
hello, was this issue resolved?

**Comment by ILG2021** [comment]
no. i have to develop a web app.

**Comment by 6uard1an** [comment]
was it solved?

**Comment by benripka** [comment]
> "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; object-src 'self'; worker-src 'blob';"

Any update on this? Manifest V3 does not permit relaxing the CSP to load scripts form inline blob sources as previously suggested. Pity, because unless I'm mistaken this small nuance renders the entire SDK useless for chrome extension.

**Comment by benripka** [comment]
Oops I spoke to soon. The beautiful people at Microsoft left us a super helpful method on the PCMRecorder class to set the worker URL Here's how to get it working in an extension under manifest V3:

1. Copy [microsoft's audio worklet js file](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/d72c8133d6371089bf6d1e3e8a72e6aa8642f377/src/audioworklet/speech-processor.js#L5) into your extension and make sure it's accessible.
2.  Call setWorkletUrl when you are setting up your azure AudioConfig. To do so you'll need to instantiate it yourself rather than using the AudioConfig builder methods. For me I was using `AudioConfig.fromStreamInput()` before, so I just surfaced up that implementation to get access to the PCMRecorder instance:

```
import { PcmRecorder } from "microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/Exports";
import { MicAudioSource } from "microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/Exports";
import { AudioConfigImpl } from "microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/Audio/AudioConfig.js";
import * as sdk from "microsoft-cognitiveservices-speech-sdk";

// When you need to instantiate an azure recognizer, etc:

const createAudioConfig: sdk.AudioConfig = (workletPath: string) => {
  const pcmRecorder = new PcmRecorder(false);
  pcmRecorder.setWorkletUrl(
    chrome.runtime.getURL(workletPath),
  );
  
  const audioConfig = new AudioConfigImpl(
    new MicAudioSource(pcmRecorder, undefined, undefined, this.stream),
  );
}

// Now you can use the SDK as you like...
```

If you're using a method other than AudioConfig.fromStreamInput() maybe have a peek into your builders implementation and adjust as required.

**Comment by benripka** [comment]
Oops I spoke to soon. The beautiful people at Microsoft left us a super helpful method on the PCMRecorder class to set the worker URL Here's how to get it working in an extension under manifest V3:

Copy [microsoft's audio worklet js file](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/d72c8133d6371089bf6d1e3e8a72e6aa8642f377/src/audioworklet/speech-processor.js#L5) into your extension and make sure it's accessible.
Call setWorkletUrl when you are setting up your azure AudioConfig. To do so you'll need to instantiate it yourself rather than using the AudioConfig builder methods. For me I was using AudioConfig.fromStreamInput() before, so I just surfaced up that implementation to get access to the PCMRecorder instance:
import { PcmRecorder } from "microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/Exports";
import { MicAudioSource } from "microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/Exports";
import { AudioConfigImpl } from "microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/Audio/AudioConfig.js";
import * as sdk from "microsoft-cognitiveservices-speech-sdk";

// When you need to instantiate an azure recognizer, etc:

const createAudioConfig: sdk.AudioConfig = (workletPath: string) => {
  const pcmRecorder = new PcmRecorder(false);
  pcmRecorder.setWorkletUrl(
    chrome.runtime.getURL(workletPath),
  );
  
  const audioConfig = new AudioConfigImpl(
    new MicAudioSource(pcmRecorder, undefined, undefined, this.stream),
  );
}

// Now you can use the SDK as you like...

**Comment by glharper** [comment]
@benripka There's a string property you can use to set that workletUrl as well...
```
const createAudioConfig: sdk.AudioConfig = (workletPath: string) => { 
  const audioConfig = [...];
  audioConfig.setProperty("MICROPHONE-WorkletSourceUrl", chrome.runtime.getURL(workletPath));
}
```

**Comment by benripka** [comment]
> @benripka There's a string property you can use to set that workletUrl as well...
> 
> ```
> const createAudioConfig: sdk.AudioConfig = (workletPath: string) => { 
>   const audioConfig = [...];
>   audioConfig.setProperty("MICROPHONE-WorkletSourceUrl", chrome.runtime.getURL(workletPath));
> }
> ```

^ Oh awesome, much better. Thanks @glharper.

**Comment by benripka** [comment]
Strangely, setting the worklet URL seems to work great, but only up until speechEndDetected fires. At that point it seems to crash right away, because it reverts back to using the inline script, resulting in:

```Refused to create a worker from 'data:text/javascript;base64,<etc..>' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.```

Any ideas on why that might be happening? Is the worklet or audio context torn down when silence is detected?
