### ISSUE TITLE
Question: What is the initial value of PropertyId.InitialSilenceTimeout_Ms in SpeechConfig

### ISSUE THREAD

**Issue by saurabhpati** [microsoft/cognitive-services-speech-sdk-js#667]
I want to know the initial silence timeout in speech config. For me, the recognizeOnceAsync is taking 30s to trigger the NoMatch reason without setting any value. Can I know what is the InitialSilenceTimeout_Ms? is it 30 sec? Are there any existing issues related to Initial silence timeout that I should know of before setting it?

**Comment by glharper** [comment]
@saurabhpati Thank you for using JS Speech SDK, and writing this issue up. All silence timeout defaults (including initial silence timeout) are service dependent. There's a thread explaining timeout behavior [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/502), but we understand there has been a change in default recently as our service backend has upgraded to a newer version of the service protocol. 

I will forward this item to our service team.

**Comment by saurabhpati** [comment]
@glharper thanks for your response, I have gone through the thread already but its not clear whether the default values are same for all language specific libraries or different.

Are they same?

I also went through the documentation at this link: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-recognize-speech?pivots=programming-language-csharp#change-how-silence-is-handled, This section _Change how silence is treated_ mentions the your typical default of 5 seconds but does so only for the c# documentation and not for Javascript one, so it is not clear whether this is applicable only for c# sdk or also for the javascript section.

Can you please clarify these for me?

we are using the 1.18.1 version of this package, what should we expect the default value of the initial silence timeout to be?

**Comment by glharper** [comment]
@saurabhpati The Speech SDKs for all supported languages (JavaScript, C#, C++, Java, Python, and Go) connect to a backend speech service that provides the speech detection for your audio stream. That backend service sets the default timeout, so the SDK has no control over the default timeout.

Because of a recent upgrade on the backend service side, a bug was introduced, and the default timeout changed, but the default timeout should return to 5s within the next couple of weeks when the hotfix is rolled out.

So to answer your question, the default timeouts are the same for all languages, because the SDKs for all languages connect to the same speech service.

**Comment by saurabhpati** [comment]
@glharper Thanks. That answers my questions.
