### ISSUE TITLE
[Bug]: Failed to stop transcriber "Another turn started before current completed."

### ISSUE THREAD

**Issue by matt-carbon** [microsoft/cognitive-services-speech-sdk-js#753]
### What happened?

Our logging shows that on calling the `SpeechRecognizer` `stopContinuousRecognitionAsync` function, we see an error message saying `Another turn started before current completed.`.

I tried looking through the library but it seems this is also unexpected from the sdk:
https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/ee95b6997f5db9298ee77e578deea72a88cb1a67/src/common.speech/RequestSession.ts#L178

I've recently upgraded web sdk to 1.32.0 but below in the `version` dropdown I cannot select that value.

When this happens, does it mean the transcriber has not stopped? Or was previously stopped? Or something else?

Thanks!

### Version

1.31.0 (Edge)

### What browser/platform are you seeing the problem on?

Chrome

### Relevant log output

```shell
Unfortunately I do not have a local log of this and only have sentry reports of the issue.
```

**Comment by glharper** [comment]
Hi @matt-carbon, thank you for using JS Speech SDK and writing this issue up. AFAICT from the code, that message is more informative than an error condition. The turn.start is a service message stating a new speaking turn has begun, and shouldn't impact operation. Are you seeing an impact?

**Comment by matt-carbon** [comment]
Thanks @glharper! These logs are coming back through our sentry monitoring and we've seen some different recording bugs. So I'm trying to track them down. This may be a red herring given what you've said. Are there docs related to speaking turns? The error and message look confusing in terms of single microphone recording. I would love to learn more about those aspects to completely rule this out

**Comment by glharper** [comment]
@matt-carbon We don't have any public-facing docs on how turns work, but if you were seeing the websocket messages for a long recognition session, you should see "turn.start," then several "speech.phrase", then "turn.end", then repeat that cycle. This error seems to happen when two or more "turn.start" messages are received from the service before a "turn.end". Not sure what the root cause would be exactly, but network instability is a possibility.

For figuring out why the SDK is getting an out-of-order "turn.start", an actual log would be helpful: see [this page](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging)

**Comment by matt-carbon** [comment]
Got it, thanks @glharper! In that case I will close this issue. I can reopen if it turns out to be something unexpected and will follow your log suggestion.

Thanks!

**Comment by nachonavarro** [comment]
Hey @matt-carbon did you figure out the reason? I'm having exactly the same issues, Sentry reporting "Another turn started before current completed."

It happens sporadically...

**Comment by matt-carbon** [comment]
@nachonavarro we ended up moving to a backend transcription solution as it's more robust and less dependent on client network issues
