### ISSUE TITLE
Keyword Spotting Implementation

### ISSUE THREAD

**Issue by ZaherAirout** [microsoft/cognitive-services-speech-sdk-js#80]
I want to use custom wake word but it throws an exception `Uncaught Error: Not yet implemented.`
Is there any way to use it?
if not, how long does it take to be implemented?
Thanks.

**Comment by wolfma61** [comment]
check here:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/scenario-availability

Wake Word (Keyword Spotter/KWS)
C++/Windows & Linux
C#/Windows & Linux
Python/Windows & Linux
Java/Windows & Linux & Android (Speech Devices SDK)
Wake Word (Keyword Spotter/KWS) functionality might work with any microphone type, official KWS support, however, is currently limited to the microphone arrays found in the Azure Kinect DK hardware or the Speech Devices SDK

it is a desired feature for JS, but not on the short list. No ETA

**Comment by oscholz** [comment]
@ZaherAirout We realistically won't implement this anytime soon, so we are going to resolve this ticket for the time being. We don't see the use case for keyword spotting as super important for JavaScript. If you disagree, please reactivate this issue, and describe the use case you want to implement. Most of our work is driven by customer priorities.
Thank you for using the JS Speech SDK.

**Comment by chevtek** [comment]
Is there a recommended alternative for keyword spotting in NodeJS? My team is creating a discord bot that provides voice recognition commands. We've implemented this ability using the Azure Speech JavaScript SDK and it works great except for the fact that it basically has to continuously recognize speech and then we have to parse the text to find the keyword and go from there.

This would be fine if it wasn't for the fact that in only a handful of days a single developer has racked up $10 from the voice recognition. When the bot goes live it will have to listen continuously for hours on end day in and day out. I am worried this is going to explode the cost here. Anything you recommend for getting around this? I was hoping keyword detection would greatly reduce processing costs but it appears we're out of luck here since there's no plans to implement it in the JavaScript SDK :'(

**Comment by acmoles** [comment]
+1 to keyword spotting in the Javascript SDK. We would like to prototype AI Assistant use-cases but the lack of this ability limits our options. I would have thought that the proliferation of LLM-based assistants could greatly increase the demand for this capability in JS.
