### ISSUE TITLE
I'm looking for a way to adjust these threshold values depending on the country, but I haven't found any options or settings for that.

### ISSUE THREAD

**Issue by syama-aot** [microsoft/cognitive-services-speech-sdk-js#817]
For The following table describes the prosody assessment results in more detail:

Reference : https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-javascript

Thresholds | Suggested thresholds on both confidence scores are 0.75. That means, if the value of UnexpectedBreak – Confidence is larger than 0.75, it has an unexpected break. If the value of MissingBreak – confidence is larger than 0.75, it has a missing break. If you want to have variable detection sensitivity on these two breaks, you can assign different thresholds to the UnexpectedBreak - Confidence and MissingBreak - Confidence fields.

I'm looking for a way to adjust these threshold values depending on the country, but I haven't found any options or settings for that.

**Comment by yaden2018** [comment]
You need to define these thresholds in your own code, instead of passing them via setting or config.

We just return these values in output json: UnexpectedBreak - Confidence and MissingBreak - Confidence. Developers can compare these values with their defined thresholds to get the final decision on error types: unexpected or missing break.

BTW, 0.75 is a default value we recommend, better to adjust them based on your own scenario.

**Comment by LeoLiu-Xingchi** [comment]
@yaden2018 question: are these thresholds only returned when using json type? I don't see the confidence scores defined in SDK object: https://learn.microsoft.com/en-us/objectivec/cognitive-services/speech/spxpronunciationassessmentresult (I'm using Swift SDK).

Thank you!

**Comment by yaden2018** [comment]
You can find these scores in words part. If you can't get such info, please open a new issue if you are still interested in using this SDK. I'm not expert on SDK related issues.
